#!/bin/bash

echo "════════════════════════════════════════════════════════════"
echo "  🚀 GitHub Push Instructions for Shadow Spending Detector"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ Git repository is already initialized!"
echo "✅ All files are committed!"
echo "✅ Ready to push to GitHub!"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  📋 STEP-BY-STEP INSTRUCTIONS"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "STEP 1: Create GitHub Repository"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://github.com/new"
echo ""
echo "2. Fill in:"
echo "   Repository name: shadow-spending-detector"
echo "   Description: AI-powered subscription and spending pattern detector"
echo "   Public: ✓ (check this)"
echo "   ✗ Do NOT initialize with README, .gitignore, or license"
echo ""
echo "3. Click 'Create repository'"
echo ""
echo "4. You'll see a page with commands - IGNORE those!"
echo "   Use the commands below instead."
echo ""

echo "STEP 2: Get Your GitHub Repository URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After creating the repo, copy your repository URL."
echo "It will look like:"
echo "   https://github.com/YOUR_USERNAME/shadow-spending-detector.git"
echo ""
echo "Replace YOUR_USERNAME with your actual GitHub username!"
echo ""

echo "STEP 3: Run These Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Copy and run these commands ONE BY ONE:"
echo ""
echo "# Navigate to project directory"
echo "cd /app"
echo ""
echo "# Add your GitHub repository (REPLACE YOUR_USERNAME)"
echo "git remote add origin https://github.com/YOUR_USERNAME/shadow-spending-detector.git"
echo ""
echo "# Push to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "If prompted for credentials:"
echo "  Username: (your GitHub username)"
echo "  Password: (use Personal Access Token, NOT your password)"
echo ""

echo "STEP 4: Get Personal Access Token (If Needed)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "GitHub requires a Personal Access Token instead of password:"
echo ""
echo "1. Go to: https://github.com/settings/tokens"
echo "2. Click 'Generate new token' → 'Generate new token (classic)'"
echo "3. Name: 'Shadow Spending Detector Deploy'"
echo "4. Expiration: 90 days"
echo "5. Scopes: Check 'repo' (full control of private repositories)"
echo "6. Click 'Generate token'"
echo "7. COPY THE TOKEN (you'll only see it once!)"
echo "8. Use this token as password when pushing"
echo ""

echo "STEP 5: Verify on GitHub"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After pushing, go to:"
echo "   https://github.com/YOUR_USERNAME/shadow-spending-detector"
echo ""
echo "You should see:"
echo "   ✓ All your files"
echo "   ✓ README.md displayed"
echo "   ✓ Latest commit: 'Shadow Spending Detector - Production ready'"
echo ""

echo "STEP 6: Deploy to Vercel"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://vercel.com/new"
echo ""
echo "2. Click 'Continue with GitHub'"
echo ""
echo "3. Select 'shadow-spending-detector' repository"
echo ""
echo "4. Configure Project:"
echo "   Framework Preset: Next.js (auto-detected)"
echo "   Root Directory: ./"
echo "   Build Command: next build (default)"
echo "   Output Directory: .next (default)"
echo ""
echo "5. Add Environment Variables (click 'Environment Variables'):"
echo ""
echo "   Name: NEXT_PUBLIC_SUPABASE_URL"
echo "   Value: https://kqyuyybpktxmeyufdjgi.supabase.co"
echo ""
echo "   Name: NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxeXV5eWJwa3R4bWV5dWZkamdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5OTAzMzksImV4cCI6MjA4OTU2NjMzOX0.ga6Tqe9MXC_1mAjPXKIPL_Lt_QZfCKMzaXnt2APptNY"
echo ""
echo "   Name: SUPABASE_SERVICE_ROLE_KEY"
echo "   Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxeXV5eWJwa3R4bWV5dWZkamdpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mzk5MDMzOSwiZXhwIjoyMDg5NTY2MzM5fQ.qujJJatxokMnaVTm8W4pP_XLwW7aJo-beWbL6O0UuFI"
echo ""
echo "6. Click 'Deploy'"
echo ""
echo "7. Wait 2-3 minutes... ⏳"
echo ""
echo "8. ✅ Your app will be live at: https://shadow-spending-detector.vercel.app"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  🎉 AFTER DEPLOYMENT"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Update Supabase Settings:"
echo "   Go to: https://supabase.com/dashboard/project/kqyuyybpktxmeyufdjgi/settings/general"
echo "   Change Site URL to: https://your-project-name.vercel.app"
echo ""
echo "2. Test your live app!"
echo ""
echo "3. Share it:"
echo "   - Add to LinkedIn"
echo "   - Add to Resume"
echo "   - Add to Portfolio"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  📝 QUICK REFERENCE"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "GitHub Repo URL Format:"
echo "  https://github.com/YOUR_USERNAME/shadow-spending-detector.git"
echo ""
echo "Commands to Push:"
echo "  cd /app"
echo "  git remote add origin https://github.com/YOUR_USERNAME/shadow-spending-detector.git"
echo "  git push -u origin main"
echo ""
echo "Vercel Deploy:"
echo "  https://vercel.com/new"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  🆘 TROUBLESHOOTING"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Error: 'remote origin already exists'"
echo "  Fix: git remote remove origin"
echo "  Then: git remote add origin <your-url>"
echo ""
echo "Error: 'authentication failed'"
echo "  Fix: Use Personal Access Token instead of password"
echo "  Get token at: https://github.com/settings/tokens"
echo ""
echo "Error: Vercel build fails"
echo "  Fix: Make sure all environment variables are added"
echo "  Check: All 3 Supabase variables must be present"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  ✅ YOU'RE READY!"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "Your project is committed and ready to push!"
echo ""
echo "Next steps:"
echo "  1. Create GitHub repo"
echo "  2. Run the push commands (replace YOUR_USERNAME)"
echo "  3. Deploy on Vercel"
echo "  4. Celebrate! 🎉"
echo ""
