#!/bin/bash

# Script to help configure Supabase settings properly

echo "════════════════════════════════════════════════════════════"
echo "  🔧 Supabase Configuration Helper"
echo "════════════════════════════════════════════════════════════"
echo ""

PROJECT_REF="kqyuyybpktxmeyufdjgi"
SITE_URL="https://spend-shadow.preview.emergentagent.com"

echo "📋 Your Supabase Project:"
echo "   Project: $PROJECT_REF"
echo "   Site URL: $SITE_URL"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  ⚠️  IMPORTANT: Manual Configuration Required"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "Supabase requires MANUAL configuration in the dashboard."
echo "Please follow these exact steps:"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 STEP 1: Disable Email Confirmation (EASIEST FIX)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open this URL in your browser:"
echo "   👉 https://supabase.com/dashboard/project/$PROJECT_REF/auth/providers"
echo ""
echo "2. Scroll down to 'Email' section"
echo ""
echo "3. Find the toggle that says:"
echo "   'Confirm email' or 'Enable email confirmations'"
echo ""
echo "4. TURN IT OFF (disable it)"
echo ""
echo "5. Click the 'Save' button at the bottom"
echo ""
echo "✅ After this, signup will work WITHOUT email confirmation!"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 STEP 2: Update Site URL (Optional, for email links)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open this URL:"
echo "   👉 https://supabase.com/dashboard/project/$PROJECT_REF/settings/general"
echo ""
echo "2. Find 'Site URL' field"
echo ""
echo "3. Change it to:"
echo "   $SITE_URL"
echo ""
echo "4. Click 'Save'"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📌 STEP 3: Add Redirect URLs (Optional)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Open this URL:"
echo "   👉 https://supabase.com/dashboard/project/$PROJECT_REF/auth/url-configuration"
echo ""
echo "2. Under 'Redirect URLs', add these (one by one):"
echo "   - $SITE_URL/**"
echo "   - $SITE_URL/dashboard"
echo "   - $SITE_URL/auth/callback"
echo ""
echo "3. Click 'Add URL' for each"
echo "4. Click 'Save'"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  🎯 RECOMMENDED: Just Do STEP 1"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "STEP 1 (disable email confirmation) is all you need for testing!"
echo "After that, you can:"
echo "  ✅ Sign up instantly"
echo "  ✅ Login immediately"
echo "  ✅ No email verification needed"
echo "  ✅ Start using the app right away!"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  ⚡ Quick Test After Configuration"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. Go to: $SITE_URL"
echo "2. Click 'Sign Up'"
echo "3. Email: test123@test.com"
echo "4. Password: Test123!"
echo "5. Click 'Create Account'"
echo "6. Should auto-login and show dashboard! ✅"
echo ""

echo "════════════════════════════════════════════════════════════"
echo "  Need Help? Check these files:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  📄 /app/FIX_EMAIL_CONFIRMATION.md"
echo "  📄 /app/FIX_SITE_CANT_BE_REACHED.md"
echo "  📄 /app/SETUP_GUIDE.md"
echo ""
echo "════════════════════════════════════════════════════════════"
